/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Manage.QuanLySQL;
import Models.Reviews;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jimbe
 */
public class DSDanhGia extends javax.swing.JFrame {

    String filter = "No";
    QuanLySQL ql = new QuanLySQL();

    void load(ArrayList<Reviews> list) {
        DefaultTableModel model = (DefaultTableModel) tblDG.getModel();
        model.setRowCount(0);
        for (Reviews reviews : list) {
            model.addRow(new Object[]{
                reviews.getNgayDanhGia(), reviews.getSoSao()
            });
        }
    }

    /**
     * Creates new form QLDanhGia
     */
    public DSDanhGia() {
        initComponents();
        load(ql.getReviewsList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDG = new javax.swing.JTable();
        labelSS = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNDDANHGIA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cboFilter = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách đánh giá");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("<<Back");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        tblDG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày đánh giá", "Số sao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDG);

        labelSS.setText("Số sao:");

        labelDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDate.setText("Đánh giá ngày:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nội dung:");

        txtNDDANHGIA.setEditable(false);
        txtNDDANHGIA.setColumns(20);
        txtNDDANHGIA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNDDANHGIA.setRows(5);
        jScrollPane2.setViewportView(txtNDDANHGIA);

        jLabel3.setText("Chọn số sao");

        cboFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        btnFilter.setText("Lọc");
        btnFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFilterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(labelDate)
                    .addComponent(labelSS)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFilter))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(cboFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSS)
                .addGap(18, 18, 18)
                .addComponent(labelDate)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new ManagerMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tblDGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDGMouseClicked
        if (filter.equals("Yes")) {
            ArrayList<Reviews> templist = new ArrayList<>();
            for(Reviews rev : ql.getReviewsList()){
                if(rev.getSoSao() == Integer.parseInt(cboFilter.getSelectedItem().toString())){
                templist.add(rev);
                }
            }
            int row = tblDG.getSelectedRow();
            Reviews review = templist.get(row);
            txtNDDANHGIA.setText(review.getNDDanhGia());
            labelDate.setText("Đánh giá ngày: " + review.getNgayDanhGia());
            if (review.getSoSao() == 1) {
                labelSS.setText("Số sao: ⭐");
            } else if (review.getSoSao() == 2) {
                labelSS.setText("Số sao: ⭐⭐");
            } else if (review.getSoSao() == 3) {
                labelSS.setText("Số sao: ⭐⭐⭐");
            } else if (review.getSoSao() == 4) {
                labelSS.setText("Số sao: ⭐⭐⭐⭐");
            } else {
                labelSS.setText("Số sao: ⭐⭐⭐⭐⭐");
            }
        } else {
            int row = tblDG.getSelectedRow();
            Reviews review = ql.getReviewsList().get(row);
            txtNDDANHGIA.setText(review.getNDDanhGia());
            labelDate.setText("Đánh giá ngày: " + review.getNgayDanhGia());
            if (review.getSoSao() == 1) {
                labelSS.setText("Số sao: ⭐");
            } else if (review.getSoSao() == 2) {
                labelSS.setText("Số sao: ⭐⭐");
            } else if (review.getSoSao() == 3) {
                labelSS.setText("Số sao: ⭐⭐⭐");
            } else if (review.getSoSao() == 4) {
                labelSS.setText("Số sao: ⭐⭐⭐⭐");
            } else {
                labelSS.setText("Số sao: ⭐⭐⭐⭐⭐");
            }
        }
    }//GEN-LAST:event_tblDGMouseClicked

    private void btnFilterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilterMouseClicked
        filter = "Yes";
        String filter = cboFilter.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) tblDG.getModel();
        model.setRowCount(0);
        ArrayList<Reviews> list = ql.getReviewsList();
        for (Reviews reviews : list) {
            if (Integer.toString(reviews.getSoSao()).equals(filter)) {
                model.addRow(new Object[]{
                    reviews.getNgayDanhGia(), reviews.getSoSao()
                });
            }
        }
    }//GEN-LAST:event_btnFilterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSDanhGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSDanhGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSDanhGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSDanhGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSDanhGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JComboBox<String> cboFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelSS;
    private javax.swing.JTable tblDG;
    private javax.swing.JTextArea txtNDDANHGIA;
    // End of variables declaration//GEN-END:variables
}
