/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Manage.QuanLySQL;
import Models.Bills;
import Models.Cart;
import Models.Coupons;
import Models.Products;
import java.awt.Color;
import java.awt.Image;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jimbe
 */
public class MuaHang extends javax.swing.JFrame {
    public static MuaHang Instance;
    public JTextField txtuserz;
    QuanLySQL ql = new QuanLySQL();
    Integer displayProd = 0;
    Integer buy = 0;
    String discountUse = "no";
    String savecode;
    Integer saveDiscount;
    ArrayList<Cart> cartItems = new ArrayList<>();

    void loadCart(ArrayList<Cart> list) {
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        model.setRowCount(0);
        for (Cart cart : list) {
            model.addRow(new Object[]{
                cart.getProduct(), cart.getAmount(), cart.getTotal()
            });
        }
        Float yestotal = (float) 0;
        for (Cart cartItem : cartItems) {
            yestotal += cartItem.getTotal();
        }
        labelTong.setText("Tổng: " + yestotal);
    }

    void load(Products prod) {
        labelSanPham.setText("Sản phẩm: " + prod.getTenSP() + " (" + ql.getProductsList().get(displayProd).getSoLuong() + ")");
        labelGia.setText("Giá: " + prod.getGia());
        ImageIcon img = new ImageIcon(prod.getImg());
        Image original = img.getImage();
        Image resize = original.getScaledInstance(200, 175, Image.SCALE_SMOOTH);
        ImageLabel.setIcon(new ImageIcon(resize));
        ImageLabel.setBorder(BorderFactory.createLineBorder(Color.black, 5));
    }

    /**
     * Creates new form MuaHang
     */
    public MuaHang() {
        initComponents();
        Instance = this;
        txtuserz = txtuser;
        load(ql.getProductsList().get(displayProd));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageLabel = new javax.swing.JLabel();
        labelSanPham = new javax.swing.JLabel();
        labelGia = new javax.swing.JLabel();
        labelMua = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();
        remove1 = new javax.swing.JButton();
        add10 = new javax.swing.JButton();
        remove10 = new javax.swing.JButton();
        btnChuyen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelTong = new javax.swing.JLabel();
        addToCartButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaGiamGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnCoupon = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cboPhuongThuc = new javax.swing.JComboBox<>();
        btnDelAll = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtDelFromCart = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(990, 308));

        ImageLabel.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        ImageLabel.setText(".");

        labelSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSanPham.setText("Sản phẩm:");

        labelGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelGia.setText("Giá:");

        labelMua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMua.setText("Mua: 0");

        add1.setText("+1");
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
        });

        remove1.setText("-1");
        remove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remove1MouseClicked(evt);
            }
        });

        add10.setText("+10");
        add10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add10MouseClicked(evt);
            }
        });

        remove10.setText("-10");
        remove10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                remove10MouseClicked(evt);
            }
        });

        btnChuyen.setText("Chuyển");
        btnChuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChuyenMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Chuyển sản phẩm");

        labelTong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTong.setText("Tổng: 0 ");

        addToCartButton.setText("Thêm vào giỏ");
        addToCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCartButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nhập mã giảm giá:");

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sản phẩm", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("<<Back");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        btnCoupon.setText("Xác nhận");
        btnCoupon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCouponMouseClicked(evt);
            }
        });

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Chọn phương thức:");

        cboPhuongThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thẻ", "Zalo Pay", "MoMo", "Ngân hàng" }));

        btnDelAll.setText("Xóa hết");
        btnDelAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelAllMouseClicked(evt);
            }
        });

        jButton1.setText("Xóa");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("VND");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Địa chỉ:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Người thanh toán:");

        txtuser.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelGia)
                                    .addComponent(labelSanPham)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnChuyen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelMua)
                                        .addGap(18, 18, 18)
                                        .addComponent(add1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(remove1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(add10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(remove10))
                                    .addComponent(jLabel3)
                                    .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addToCartButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDelFromCart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButton1)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(btnThanhToan)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPhuongThuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCoupon))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLabel)
                .addGap(17, 17, 17)
                .addComponent(labelSanPham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnChuyen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelGia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMua)
                    .addComponent(add1)
                    .addComponent(remove1)
                    .addComponent(add10)
                    .addComponent(remove10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToCartButton)
                    .addComponent(btnDelAll)
                    .addComponent(jButton1)
                    .addComponent(txtDelFromCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoupon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTong)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboPhuongThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnThanhToan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add10MouseClicked
        // TODO add your handling code here:
        if (buy >= ql.getProductsList().get(displayProd).getSoLuong()) {
            buy = ql.getProductsList().get(displayProd).getSoLuong();
            labelMua.setText("Mua: " + buy);
            return;
        }
        buy += 10;
        labelMua.setText("Mua: " + buy);
        String gia = labelGia.getText().substring(5);
    }//GEN-LAST:event_add10MouseClicked

    private void btnChuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChuyenMouseClicked
        if (displayProd == ql.getProductsList().size() - 1) {
            displayProd = 0;
        } else {
            displayProd += 1;
        }
        load(ql.getProductsList().get(displayProd));
        buy = 0;
        labelMua.setText("Mua: 0");
    }//GEN-LAST:event_btnChuyenMouseClicked

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
        if (buy >= ql.getProductsList().get(displayProd).getSoLuong()) {
            buy = ql.getProductsList().get(displayProd).getSoLuong();
            labelMua.setText("Mua: " + buy);
            return;
        }
        buy += 1;
        labelMua.setText("Mua: " + buy);
        String gia = labelGia.getText().substring(5);
    }//GEN-LAST:event_add1MouseClicked

    private void remove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remove1MouseClicked
        // TODO add your handling code here:
        if (buy < 1) {
        } else {
            buy -= 1;
            labelMua.setText("Mua: " + buy);
        }
        String gia = labelGia.getText().substring(5);
    }//GEN-LAST:event_remove1MouseClicked

    private void remove10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remove10MouseClicked
        // TODO add your handling code here:
        if (buy < 10) {
        } else {
            buy -= 10;
            labelMua.setText("Mua: " + buy);
        }
        String gia = labelGia.getText().substring(5);
    }//GEN-LAST:event_remove10MouseClicked

    private void addToCartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartButtonMouseClicked
        // TODO add your handling code here:
        Products prod = ql.getProductsList().get(displayProd);
        String name = prod.getTenSP();
        Integer amount = buy;
        Float total = prod.getGia() * buy;
        if (buy == 0) {
            JOptionPane.showMessageDialog(this, "Phải mua ít nhất 1 đơn vị");
            return;
        }
        Cart tempcart = new Cart();
        for (Cart cartcheck : cartItems) {
            if (name.equals(cartcheck.getProduct())) {
                amount += cartcheck.getAmount();
                total += cartcheck.getTotal();
                tempcart = cartcheck;
            }
        }

        Cart cart = new Cart(name, amount, total);
        cartItems.add(cart);
        try {
            cartItems.remove(tempcart);
        } catch (Exception e) {
            loadCart(cartItems);
        }

        loadCart(cartItems);
    }//GEN-LAST:event_addToCartButtonMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new CustomerMenu().setVisible(true);
        CustomerMenu.Instance.txtuserz.setText(txtuser.getText());
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCouponMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCouponMouseClicked
        // TODO add your handling code here:
        try {
            Coupons coupon = new Coupons();
            for (Coupons couponz : ql.getCouponList()) {
                if (couponz.getID().trim().equals(txtMaGiamGia.getText())) {
                    coupon = couponz;
                }
            }
            if (coupon.getTrangThai()) {
                discountUse = "yes";
                savecode = txtMaGiamGia.getText();
                saveDiscount = coupon.getPhanTramGiam();
            } else {
                JOptionPane.showMessageDialog(this, "Phiếu giảm giá này không còn hoạt động");
                return;
            }
            Float tong = Float.parseFloat(labelTong.getText().substring(6).trim());
            labelTong.setText("Tổng: " + tong * (100 - coupon.getPhanTramGiam()) / 100);
            JOptionPane.showMessageDialog(this, "Bạn đã được giảm " + coupon.getPhanTramGiam() + "%");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Mã giảm giá không tồn tại");
        }
    }//GEN-LAST:event_btnCouponMouseClicked

    private void btnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseClicked
        // TODO add your handling code here
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String giamGia;
            if (discountUse.equals("yes")) {
                ql.usedCoupon(savecode.trim());
                giamGia = saveDiscount + "%";
            } else {
                giamGia = "Không";
            }
            String chiTiet = "";
            int i = 0;
            for (Cart cart : cartItems) {
                if (i == 0 && cartItems.size() == 1) {
                    chiTiet = chiTiet + cart.getProduct() + " x" + cart.getAmount() + ".";
                } else if (cartItems.size() > 1 && i != cartItems.size() - 1) {
                    chiTiet = chiTiet + cart.getProduct() + " x" + cart.getAmount() + ", ";
                } else if (i == cartItems.size() - 1) {
                    chiTiet = chiTiet + cart.getProduct() + " x" + cart.getAmount() + ".";
                }
                i++;
            }
            i = 0;
            LocalDate currentDate = LocalDate.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String ngayThanhToan = currentDate.format(formatter);
            Float tongTien = Float.parseFloat(labelTong.getText().trim().substring(6));
            String phuongThuc = cboPhuongThuc.getSelectedItem().toString();
            String trangThai = "Đang chờ";
            String ngmua = txtuser.getText();
            String diachi = txtDiaChi.getText();
            if(diachi.trim().isBlank()){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ");
            }
            Bills bill = new Bills(chiTiet, ngayThanhToan, tongTien, trangThai, giamGia, phuongThuc, diachi, ngmua);
            Boolean kq = ql.addBill(bill);
            int j = 0;
            String delprod;
            Integer left;
            if (kq) {
                for (Cart cart : cartItems) {
                    if (cart.getProduct().trim().equals(ql.getProductsList().get(j).getTenSP())) {
                        delprod = cart.getProduct();
                        left = ql.getProductsList().get(j).getSoLuong() - cart.getAmount();
                        ql.updateProductAmount(delprod, left);
                    }
                    j++;
                }
                JOptionPane.showMessageDialog(this, "Thanh toán thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Thanh toán thất bại");
            }
            saveDiscount = null;
            savecode = null;
        } else {
            JOptionPane.showMessageDialog(this, "Đã hủy thanh toán, đã khôi phục phiếu giảm giá");
        }
    }//GEN-LAST:event_btnThanhToanMouseClicked

    private void btnDelAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelAllMouseClicked
        // TODO add your handling code here:
        cartItems.clear();
        labelTong.setText("Tổng: 0");
        loadCart(cartItems);
    }//GEN-LAST:event_btnDelAllMouseClicked

    private void tblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMouseClicked
        // TODO add your handling code here:
        int row = tblCart.getSelectedRow();
        Cart cart = cartItems.get(row);
        txtDelFromCart.setText(cart.getProduct());
    }//GEN-LAST:event_tblCartMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Cart tempProd = new Cart();
        for (Cart cart : cartItems) {
            if (cart.getProduct().equals(txtDelFromCart.getText().trim())) {
                tempProd = cart;
            }
        }
        cartItems.remove(tempProd);
        loadCart(cartItems);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuaHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JButton add1;
    private javax.swing.JButton add10;
    private javax.swing.JButton addToCartButton;
    private javax.swing.JButton btnChuyen;
    private javax.swing.JButton btnCoupon;
    private javax.swing.JButton btnDelAll;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cboPhuongThuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelGia;
    private javax.swing.JLabel labelMua;
    private javax.swing.JLabel labelSanPham;
    private javax.swing.JLabel labelTong;
    private javax.swing.JButton remove1;
    private javax.swing.JButton remove10;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtDelFromCart;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaGiamGia;
    public javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
